name: "Build with MPLABX and XC8"
description: "This action builds an MPLABX/XC8 project in a Linux container."
branding:
  icon: wind
  color: blue

inputs:
  project:
    description: Project folder location
    required: true
  configuration:
    description: Configuration to build
    required: true
    default: "default"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.project }}
    - ${{ inputs.configuration }}
